scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['58.84.0.87:8080']
      labels:
        application: 'No Agent'
    - targets: ['58.84.0.89:8080']
      labels:
        application: 'Have Agent'