scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ['10.76.0.12:8090']
      labels:
        application: 'Have Agent'
    - targets: ['10.76.0.14:8090']
      labels:
        application: 'No Agent'

# .......................