receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger:
    endpoint: "allinone:14250"
    tls:
      insecure: true
  # datadog:
  #   api:
  #     key: "0849acfc7bb55ea1ec84f32d926326a9"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [jaeger]