receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp:
    endpoint: 10.76.0.10:4317


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    # metrics:
    #   receivers: [otlp]
    #   processors: [batch]
    #   exporters: [jaeger]